// <auto-generated />
using System;
using ErrorLogDashboard.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ErrorLogDashboard.Web.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251210163753_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ErrorLogDashboard.Web.Models.ErrorLog", b =>
                {
                    b.Property<Guid>("IdErrorLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdProject")
                        .HasColumnType("char(36)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("StackTrace")
                        .HasColumnType("longtext");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Summary")
                        .HasColumnType("longtext");

                    b.HasKey("IdErrorLog");

                    b.HasIndex("IdProject");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("ErrorLogDashboard.Web.Models.Project", b =>
                {
                    b.Property<Guid>("IdProject")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ApiKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdUser")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecurityKey")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TechStack")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdProject");

                    b.HasIndex("IdUser");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ErrorLogDashboard.Web.Models.SubscriptionPlan", b =>
                {
                    b.Property<Guid>("IdSubscriptionPlan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int>("MaxDailyLogs")
                        .HasColumnType("int");

                    b.Property<int>("MaxProjects")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdSubscriptionPlan");

                    b.ToTable("SubscriptionPlans");
                });

            modelBuilder.Entity("ErrorLogDashboard.Web.Models.User", b =>
                {
                    b.Property<Guid>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("IdSubscriptionPlan")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUser");

                    b.HasIndex("IdSubscriptionPlan");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ErrorLogDashboard.Web.Models.WebhookConfig", b =>
                {
                    b.Property<Guid>("IdWebhook")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("IdProject")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SecretToken")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdWebhook");

                    b.HasIndex("IdProject");

                    b.ToTable("WebhookConfigs");
                });

            modelBuilder.Entity("ErrorLogDashboard.Web.Models.ErrorLog", b =>
                {
                    b.HasOne("ErrorLogDashboard.Web.Models.Project", "Project")
                        .WithMany("ErrorLogs")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ErrorLogDashboard.Web.Models.Project", b =>
                {
                    b.HasOne("ErrorLogDashboard.Web.Models.User", "User")
                        .WithMany("Projects")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ErrorLogDashboard.Web.Models.User", b =>
                {
                    b.HasOne("ErrorLogDashboard.Web.Models.SubscriptionPlan", "SubscriptionPlan")
                        .WithMany()
                        .HasForeignKey("IdSubscriptionPlan")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubscriptionPlan");
                });

            modelBuilder.Entity("ErrorLogDashboard.Web.Models.WebhookConfig", b =>
                {
                    b.HasOne("ErrorLogDashboard.Web.Models.Project", "Project")
                        .WithMany("Webhooks")
                        .HasForeignKey("IdProject")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ErrorLogDashboard.Web.Models.Project", b =>
                {
                    b.Navigation("ErrorLogs");

                    b.Navigation("Webhooks");
                });

            modelBuilder.Entity("ErrorLogDashboard.Web.Models.User", b =>
                {
                    b.Navigation("Projects");
                });
#pragma warning restore 612, 618
        }
    }
}
